[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
no_match_path = "*/integration/*"
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
optimizer_runs = 1000000

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[profile.lite.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'xca'
